# Generated by Django 5.2.7 on 2025-10-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortenedURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField(max_length=2048)),
                ("hash", models.CharField(db_index=True, max_length=8, unique=True)),
            ],
        ),
    ]
